os: WMF 5

install:
  - ps: Install-Module Pester -Force
  - ps: Install-Module PSScriptAnalyzer -Force
  - ps: Install-Module psake -force
  - ps: Install-Module psdeploy -force

 skip_commits:
  message: /updated (readme|doc).*|update (readme|doc).*s/
  
build: false

test_script:
  - ps: .\build.ps1

 deploy_script:
  - ps: Update-ModuleManifest -Path "$PSScriptRoot\ChocoPackageUpdater\ChocoPackageUpdater.psd1" -ModuleVersion $env:APPVEYOR_BUILD_VERSION
  
      